authors:
  admin:
    name: LaFabrique.AI
    description: Creator
    avatar: https://github.com/identicons/lafabrique.png
  coulof:
    name: Coulof
    description: Author
    avatar: assets/images/coulof-avatar.png
