authors:
  admin:
    name: LaFabrique.AI
    description: Creator
    avatar: assets/images/coulof-avatar.png
  coulof:
    name: coulof
    description: Author
    avatar: assets/images/coulof-avatar.png
